ERROR - 2024-01-14 11:31:05 --> Table 'dbabsensi.perusahaan' doesn't exist
CRITICAL - 2024-01-14 11:31:05 --> Call to a member function getRow() on bool
#0 C:\xampp\htdocs\ERP-PH\system\View\View.php(210): include()
#1 C:\xampp\htdocs\ERP-PH\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\ERP-PH\system\Common.php(1089): CodeIgniter\View\View->render('agendapkl//part...', Array, true)
#3 C:\xampp\htdocs\ERP-PH\app\Controllers\agendapkl\Login.php(12): view('agendapkl//part...', Array)
#4 C:\xampp\htdocs\ERP-PH\system\CodeIgniter.php(832): App\Controllers\agendapkl\Login->index()
#5 C:\xampp\htdocs\ERP-PH\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\agendapkl\Login))
#6 C:\xampp\htdocs\ERP-PH\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ERP-PH\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ERP-PH\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2024-01-14 14:01:21 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
